/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TvDisplayRouteImport } from './routes/tv-display'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerifyQrTokenRouteImport } from './routes/verify.$qrToken'
import { Route as AuthenticatedZakatRouteImport } from './routes/_authenticated/zakat'
import { Route as AuthenticatedWelcomeRouteImport } from './routes/_authenticated/welcome'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedSubscriptionRouteImport } from './routes/_authenticated/subscription'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRolesPermissionsRouteImport } from './routes/_authenticated/roles-permissions'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedRamadanRouteImport } from './routes/_authenticated/ramadan'
import { Route as AuthenticatedQurbaniRouteImport } from './routes/_authenticated/qurbani'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPrayerTimesRouteImport } from './routes/_authenticated/prayer-times'
import { Route as AuthenticatedNoticesRouteImport } from './routes/_authenticated/notices'
import { Route as AuthenticatedMobileBankingRouteImport } from './routes/_authenticated/mobile-banking'
import { Route as AuthenticatedMembersRouteImport } from './routes/_authenticated/members'
import { Route as AuthenticatedMeetingsRouteImport } from './routes/_authenticated/meetings'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedIncomeRouteImport } from './routes/_authenticated/income'
import { Route as AuthenticatedGalleryRouteImport } from './routes/_authenticated/gallery'
import { Route as AuthenticatedExpensesRouteImport } from './routes/_authenticated/expenses'
import { Route as AuthenticatedEventsRouteImport } from './routes/_authenticated/events'
import { Route as AuthenticatedDonationsRouteImport } from './routes/_authenticated/donations'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCommitteeRouteImport } from './routes/_authenticated/committee'
import { Route as AuthenticatedCashRouteImport } from './routes/_authenticated/cash'
import { Route as AuthenticatedBankRouteImport } from './routes/_authenticated/bank'
import { Route as AuthenticatedAuditLogsRouteImport } from './routes/_authenticated/audit-logs'
import { Route as AuthenticatedAssetsRouteImport } from './routes/_authenticated/assets'

const TvDisplayRoute = TvDisplayRouteImport.update({
  id: '/tv-display',
  path: '/tv-display',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyQrTokenRoute = VerifyQrTokenRouteImport.update({
  id: '/verify/$qrToken',
  path: '/verify/$qrToken',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedZakatRoute = AuthenticatedZakatRouteImport.update({
  id: '/zakat',
  path: '/zakat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWelcomeRoute = AuthenticatedWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSubscriptionRoute =
  AuthenticatedSubscriptionRouteImport.update({
    id: '/subscription',
    path: '/subscription',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRolesPermissionsRoute =
  AuthenticatedRolesPermissionsRouteImport.update({
    id: '/roles-permissions',
    path: '/roles-permissions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRamadanRoute = AuthenticatedRamadanRouteImport.update({
  id: '/ramadan',
  path: '/ramadan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQurbaniRoute = AuthenticatedQurbaniRouteImport.update({
  id: '/qurbani',
  path: '/qurbani',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrayerTimesRoute =
  AuthenticatedPrayerTimesRouteImport.update({
    id: '/prayer-times',
    path: '/prayer-times',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNoticesRoute = AuthenticatedNoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMobileBankingRoute =
  AuthenticatedMobileBankingRouteImport.update({
    id: '/mobile-banking',
    path: '/mobile-banking',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMembersRoute = AuthenticatedMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeetingsRoute = AuthenticatedMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIncomeRoute = AuthenticatedIncomeRouteImport.update({
  id: '/income',
  path: '/income',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGalleryRoute = AuthenticatedGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExpensesRoute = AuthenticatedExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEventsRoute = AuthenticatedEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDonationsRoute = AuthenticatedDonationsRouteImport.update({
  id: '/donations',
  path: '/donations',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommitteeRoute = AuthenticatedCommitteeRouteImport.update({
  id: '/committee',
  path: '/committee',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCashRoute = AuthenticatedCashRouteImport.update({
  id: '/cash',
  path: '/cash',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBankRoute = AuthenticatedBankRouteImport.update({
  id: '/bank',
  path: '/bank',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditLogsRoute = AuthenticatedAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssetsRoute = AuthenticatedAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/tv-display': typeof TvDisplayRoute
  '/assets': typeof AuthenticatedAssetsRoute
  '/audit-logs': typeof AuthenticatedAuditLogsRoute
  '/bank': typeof AuthenticatedBankRoute
  '/cash': typeof AuthenticatedCashRoute
  '/committee': typeof AuthenticatedCommitteeRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/donations': typeof AuthenticatedDonationsRoute
  '/events': typeof AuthenticatedEventsRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/gallery': typeof AuthenticatedGalleryRoute
  '/income': typeof AuthenticatedIncomeRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/meetings': typeof AuthenticatedMeetingsRoute
  '/members': typeof AuthenticatedMembersRoute
  '/mobile-banking': typeof AuthenticatedMobileBankingRoute
  '/notices': typeof AuthenticatedNoticesRoute
  '/prayer-times': typeof AuthenticatedPrayerTimesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/qurbani': typeof AuthenticatedQurbaniRoute
  '/ramadan': typeof AuthenticatedRamadanRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/roles-permissions': typeof AuthenticatedRolesPermissionsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/subscription': typeof AuthenticatedSubscriptionRoute
  '/users': typeof AuthenticatedUsersRoute
  '/welcome': typeof AuthenticatedWelcomeRoute
  '/zakat': typeof AuthenticatedZakatRoute
  '/verify/$qrToken': typeof VerifyQrTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/tv-display': typeof TvDisplayRoute
  '/assets': typeof AuthenticatedAssetsRoute
  '/audit-logs': typeof AuthenticatedAuditLogsRoute
  '/bank': typeof AuthenticatedBankRoute
  '/cash': typeof AuthenticatedCashRoute
  '/committee': typeof AuthenticatedCommitteeRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/donations': typeof AuthenticatedDonationsRoute
  '/events': typeof AuthenticatedEventsRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/gallery': typeof AuthenticatedGalleryRoute
  '/income': typeof AuthenticatedIncomeRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/meetings': typeof AuthenticatedMeetingsRoute
  '/members': typeof AuthenticatedMembersRoute
  '/mobile-banking': typeof AuthenticatedMobileBankingRoute
  '/notices': typeof AuthenticatedNoticesRoute
  '/prayer-times': typeof AuthenticatedPrayerTimesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/qurbani': typeof AuthenticatedQurbaniRoute
  '/ramadan': typeof AuthenticatedRamadanRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/roles-permissions': typeof AuthenticatedRolesPermissionsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/subscription': typeof AuthenticatedSubscriptionRoute
  '/users': typeof AuthenticatedUsersRoute
  '/welcome': typeof AuthenticatedWelcomeRoute
  '/zakat': typeof AuthenticatedZakatRoute
  '/verify/$qrToken': typeof VerifyQrTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/tv-display': typeof TvDisplayRoute
  '/_authenticated/assets': typeof AuthenticatedAssetsRoute
  '/_authenticated/audit-logs': typeof AuthenticatedAuditLogsRoute
  '/_authenticated/bank': typeof AuthenticatedBankRoute
  '/_authenticated/cash': typeof AuthenticatedCashRoute
  '/_authenticated/committee': typeof AuthenticatedCommitteeRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/donations': typeof AuthenticatedDonationsRoute
  '/_authenticated/events': typeof AuthenticatedEventsRoute
  '/_authenticated/expenses': typeof AuthenticatedExpensesRoute
  '/_authenticated/gallery': typeof AuthenticatedGalleryRoute
  '/_authenticated/income': typeof AuthenticatedIncomeRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/meetings': typeof AuthenticatedMeetingsRoute
  '/_authenticated/members': typeof AuthenticatedMembersRoute
  '/_authenticated/mobile-banking': typeof AuthenticatedMobileBankingRoute
  '/_authenticated/notices': typeof AuthenticatedNoticesRoute
  '/_authenticated/prayer-times': typeof AuthenticatedPrayerTimesRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/qurbani': typeof AuthenticatedQurbaniRoute
  '/_authenticated/ramadan': typeof AuthenticatedRamadanRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/roles-permissions': typeof AuthenticatedRolesPermissionsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/subscription': typeof AuthenticatedSubscriptionRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/welcome': typeof AuthenticatedWelcomeRoute
  '/_authenticated/zakat': typeof AuthenticatedZakatRoute
  '/verify/$qrToken': typeof VerifyQrTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/tv-display'
    | '/assets'
    | '/audit-logs'
    | '/bank'
    | '/cash'
    | '/committee'
    | '/dashboard'
    | '/donations'
    | '/events'
    | '/expenses'
    | '/gallery'
    | '/income'
    | '/inventory'
    | '/meetings'
    | '/members'
    | '/mobile-banking'
    | '/notices'
    | '/prayer-times'
    | '/profile'
    | '/qurbani'
    | '/ramadan'
    | '/reports'
    | '/roles-permissions'
    | '/settings'
    | '/subscription'
    | '/users'
    | '/welcome'
    | '/zakat'
    | '/verify/$qrToken'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/tv-display'
    | '/assets'
    | '/audit-logs'
    | '/bank'
    | '/cash'
    | '/committee'
    | '/dashboard'
    | '/donations'
    | '/events'
    | '/expenses'
    | '/gallery'
    | '/income'
    | '/inventory'
    | '/meetings'
    | '/members'
    | '/mobile-banking'
    | '/notices'
    | '/prayer-times'
    | '/profile'
    | '/qurbani'
    | '/ramadan'
    | '/reports'
    | '/roles-permissions'
    | '/settings'
    | '/subscription'
    | '/users'
    | '/welcome'
    | '/zakat'
    | '/verify/$qrToken'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/tv-display'
    | '/_authenticated/assets'
    | '/_authenticated/audit-logs'
    | '/_authenticated/bank'
    | '/_authenticated/cash'
    | '/_authenticated/committee'
    | '/_authenticated/dashboard'
    | '/_authenticated/donations'
    | '/_authenticated/events'
    | '/_authenticated/expenses'
    | '/_authenticated/gallery'
    | '/_authenticated/income'
    | '/_authenticated/inventory'
    | '/_authenticated/meetings'
    | '/_authenticated/members'
    | '/_authenticated/mobile-banking'
    | '/_authenticated/notices'
    | '/_authenticated/prayer-times'
    | '/_authenticated/profile'
    | '/_authenticated/qurbani'
    | '/_authenticated/ramadan'
    | '/_authenticated/reports'
    | '/_authenticated/roles-permissions'
    | '/_authenticated/settings'
    | '/_authenticated/subscription'
    | '/_authenticated/users'
    | '/_authenticated/welcome'
    | '/_authenticated/zakat'
    | '/verify/$qrToken'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  TvDisplayRoute: typeof TvDisplayRoute
  VerifyQrTokenRoute: typeof VerifyQrTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tv-display': {
      id: '/tv-display'
      path: '/tv-display'
      fullPath: '/tv-display'
      preLoaderRoute: typeof TvDisplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$qrToken': {
      id: '/verify/$qrToken'
      path: '/verify/$qrToken'
      fullPath: '/verify/$qrToken'
      preLoaderRoute: typeof VerifyQrTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/zakat': {
      id: '/_authenticated/zakat'
      path: '/zakat'
      fullPath: '/zakat'
      preLoaderRoute: typeof AuthenticatedZakatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/welcome': {
      id: '/_authenticated/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof AuthenticatedWelcomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subscription': {
      id: '/_authenticated/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof AuthenticatedSubscriptionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roles-permissions': {
      id: '/_authenticated/roles-permissions'
      path: '/roles-permissions'
      fullPath: '/roles-permissions'
      preLoaderRoute: typeof AuthenticatedRolesPermissionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ramadan': {
      id: '/_authenticated/ramadan'
      path: '/ramadan'
      fullPath: '/ramadan'
      preLoaderRoute: typeof AuthenticatedRamadanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/qurbani': {
      id: '/_authenticated/qurbani'
      path: '/qurbani'
      fullPath: '/qurbani'
      preLoaderRoute: typeof AuthenticatedQurbaniRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prayer-times': {
      id: '/_authenticated/prayer-times'
      path: '/prayer-times'
      fullPath: '/prayer-times'
      preLoaderRoute: typeof AuthenticatedPrayerTimesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notices': {
      id: '/_authenticated/notices'
      path: '/notices'
      fullPath: '/notices'
      preLoaderRoute: typeof AuthenticatedNoticesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mobile-banking': {
      id: '/_authenticated/mobile-banking'
      path: '/mobile-banking'
      fullPath: '/mobile-banking'
      preLoaderRoute: typeof AuthenticatedMobileBankingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/members': {
      id: '/_authenticated/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AuthenticatedMembersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meetings': {
      id: '/_authenticated/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof AuthenticatedMeetingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/income': {
      id: '/_authenticated/income'
      path: '/income'
      fullPath: '/income'
      preLoaderRoute: typeof AuthenticatedIncomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gallery': {
      id: '/_authenticated/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof AuthenticatedGalleryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/expenses': {
      id: '/_authenticated/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AuthenticatedExpensesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events': {
      id: '/_authenticated/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AuthenticatedEventsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/donations': {
      id: '/_authenticated/donations'
      path: '/donations'
      fullPath: '/donations'
      preLoaderRoute: typeof AuthenticatedDonationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/committee': {
      id: '/_authenticated/committee'
      path: '/committee'
      fullPath: '/committee'
      preLoaderRoute: typeof AuthenticatedCommitteeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cash': {
      id: '/_authenticated/cash'
      path: '/cash'
      fullPath: '/cash'
      preLoaderRoute: typeof AuthenticatedCashRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bank': {
      id: '/_authenticated/bank'
      path: '/bank'
      fullPath: '/bank'
      preLoaderRoute: typeof AuthenticatedBankRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit-logs': {
      id: '/_authenticated/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuthenticatedAuditLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assets': {
      id: '/_authenticated/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AuthenticatedAssetsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAssetsRoute: typeof AuthenticatedAssetsRoute
  AuthenticatedAuditLogsRoute: typeof AuthenticatedAuditLogsRoute
  AuthenticatedBankRoute: typeof AuthenticatedBankRoute
  AuthenticatedCashRoute: typeof AuthenticatedCashRoute
  AuthenticatedCommitteeRoute: typeof AuthenticatedCommitteeRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDonationsRoute: typeof AuthenticatedDonationsRoute
  AuthenticatedEventsRoute: typeof AuthenticatedEventsRoute
  AuthenticatedExpensesRoute: typeof AuthenticatedExpensesRoute
  AuthenticatedGalleryRoute: typeof AuthenticatedGalleryRoute
  AuthenticatedIncomeRoute: typeof AuthenticatedIncomeRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedMeetingsRoute: typeof AuthenticatedMeetingsRoute
  AuthenticatedMembersRoute: typeof AuthenticatedMembersRoute
  AuthenticatedMobileBankingRoute: typeof AuthenticatedMobileBankingRoute
  AuthenticatedNoticesRoute: typeof AuthenticatedNoticesRoute
  AuthenticatedPrayerTimesRoute: typeof AuthenticatedPrayerTimesRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedQurbaniRoute: typeof AuthenticatedQurbaniRoute
  AuthenticatedRamadanRoute: typeof AuthenticatedRamadanRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedRolesPermissionsRoute: typeof AuthenticatedRolesPermissionsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSubscriptionRoute: typeof AuthenticatedSubscriptionRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedWelcomeRoute: typeof AuthenticatedWelcomeRoute
  AuthenticatedZakatRoute: typeof AuthenticatedZakatRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAssetsRoute: AuthenticatedAssetsRoute,
  AuthenticatedAuditLogsRoute: AuthenticatedAuditLogsRoute,
  AuthenticatedBankRoute: AuthenticatedBankRoute,
  AuthenticatedCashRoute: AuthenticatedCashRoute,
  AuthenticatedCommitteeRoute: AuthenticatedCommitteeRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDonationsRoute: AuthenticatedDonationsRoute,
  AuthenticatedEventsRoute: AuthenticatedEventsRoute,
  AuthenticatedExpensesRoute: AuthenticatedExpensesRoute,
  AuthenticatedGalleryRoute: AuthenticatedGalleryRoute,
  AuthenticatedIncomeRoute: AuthenticatedIncomeRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedMeetingsRoute: AuthenticatedMeetingsRoute,
  AuthenticatedMembersRoute: AuthenticatedMembersRoute,
  AuthenticatedMobileBankingRoute: AuthenticatedMobileBankingRoute,
  AuthenticatedNoticesRoute: AuthenticatedNoticesRoute,
  AuthenticatedPrayerTimesRoute: AuthenticatedPrayerTimesRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedQurbaniRoute: AuthenticatedQurbaniRoute,
  AuthenticatedRamadanRoute: AuthenticatedRamadanRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedRolesPermissionsRoute: AuthenticatedRolesPermissionsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSubscriptionRoute: AuthenticatedSubscriptionRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedWelcomeRoute: AuthenticatedWelcomeRoute,
  AuthenticatedZakatRoute: AuthenticatedZakatRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  TvDisplayRoute: TvDisplayRoute,
  VerifyQrTokenRoute: VerifyQrTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
